name: lib_shp_to_geojson
description: Shp to GeoJSON
version: 0.0.1
homepage: http://grappfruit.com
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  archive: ^3.3.9
  flutter:
    sdk: flutter
  freezed_annotation: ^2.3.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  proj4dart: ^2.1.0
  # can be replaced with the pub.dev dependency once the PR is merged
  shapefile:
    git:
      url: git@github.com:grAPPfruit/shapefile.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.3.3
  freezed: ^2.3.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
