name: lib_shp_to_geojson
description: Shp to GeoJSON
version: 0.0.1
homepage: http://grappfruit.com

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.9
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  shapefile: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
